(function() {var implementors = {};
implementors["antidote"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='antidote/struct.TryLockError.html' title='antidote::TryLockError'>TryLockError</a>",];
implementors["diesel"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='diesel/migrations/enum.MigrationError.html' title='diesel::migrations::MigrationError'>MigrationError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='diesel/migrations/enum.RunMigrationsError.html' title='diesel::migrations::RunMigrationsError'>RunMigrationsError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>StdError</a> for <a class='enum' href='diesel/result/enum.Error.html' title='diesel::result::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>StdError</a> for <a class='enum' href='diesel/result/enum.ConnectionError.html' title='diesel::result::ConnectionError'>ConnectionError</a>",];
implementors["libc"] = [];
implementors["libsqlite3_sys"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='libsqlite3_sys/struct.Error.html' title='libsqlite3_sys::Error'>Error</a>",];
implementors["log"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='log/struct.SetLoggerError.html' title='log::SetLoggerError'>SetLoggerError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='log/struct.ShutdownLoggerError.html' title='log::ShutdownLoggerError'>ShutdownLoggerError</a>",];
implementors["r2d2"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='r2d2/struct.InitializationError.html' title='r2d2::InitializationError'>InitializationError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='r2d2/struct.GetTimeout.html' title='r2d2::GetTimeout'>GetTimeout</a>",];
implementors["r2d2_diesel"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='r2d2_diesel/enum.Error.html' title='r2d2_diesel::Error'>Error</a>",];
implementors["regex"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='regex/enum.Error.html' title='regex::Error'>Error</a>",];
implementors["regex_syntax"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='regex_syntax/struct.Error.html' title='regex_syntax::Error'>Error</a>",];
implementors["serde"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='serde/de/value/struct.Error.html' title='serde::de::value::Error'>Error</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
